### ISSUE TITLE
Display 'H', 'M', 'S' labels

### ISSUE THREAD

**Issue by dsernst** [zippyui/react-time-picker#9]
I'm using this time picker so users can specify hours and minutes, but many have remarked they thought it was for minutes and seconds. I'd like to add an 'H' and 'M' label next to the time inputs, but it's unclear how best to go about this.

My first thought was to use `::after` pseudo-classes, but I see the individual input fields don't have classnames.

Before I go too deep on this, is there an approach you recommend?

Thanks

**Comment by dsernst** [comment]
I got something to work for now. It's hacky, but I'll share it here in case others are interested in this too:

I had already wrapped the time-picker in a `<div class='duration-config'>`. 

Then I added this LESS to my stylesheet:

```less

.duration-config {

    input {
      z-index: 2; // this is so our labels don't block the inputs' hover

      &:hover {
        background-color: rgba(0, 0, 0, 0.3) !important;
        transition: background-color .15s ease-in-out;
      }
    }

    span {
      display: none; // hide the : divider
    }

    div > div { // the first div is the whole time-picker, > div is each box

      .time-label { // this mixin is for both :afters
        color: @color;
        font-size: 21px;
        position: relative;
        bottom: 81px;
        z-index: 1;
      }

      &:first-child:after {
        .time-label;
        content: 'h';
        left: 28px;
      }
      &:last-child:after {
        .time-label;
        content: 'm';
        left: 36px;
      }
    }
  }
}
```


For those who aren't into LESS, here's the CSS it compiled into:

```css
.duration-config input {
  z-index: 2;
}
.duration-config input:hover {
  background-color: rgba(0, 0, 0, 0.3) !important;
  transition: background-color 0.15s ease-in-out;
}
.duration-config span {
  display: none;
}
.duration-config div > div .time-label {
  color: #f2f2f2;
  font-size: 21px;
  position: relative;
  bottom: 81px;
  z-index: 1;
}
.duration-config div > div:first-child:after {
  color: #f2f2f2;
  font-size: 21px;
  position: relative;
  bottom: 81px;
  z-index: 1;
  content: 'h';
  left: 28px;
}
.duration-config div > div:last-child:after {
  color: #f2f2f2;
  font-size: 21px;
  position: relative;
  bottom: 81px;
  z-index: 1;
  content: 'm';
  left: 36px;
}
```
